conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('wth.urls', namespace='wth')),
    path('captcha/', include('captcha.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG == True:
    import debug_toolbar
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

wth/urls.py
from django.urls import path

from . import views

app_name = "wth"
urlpatterns = [
    path('', views.homeview, name='home'),
    path('contact/', views.contactview, name='contact'),
    path('choose-unit/', views.unitview, name='unit'),
    path('set-city/', views.defaultcityview, name='set-city'),
    path('remove-city/', views.removecityview, name='remove-city'),
]

templates/_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0,maximum-scale=1"
        />

        <title>{% block title %} Weather {% endblock %}</title>
        <!-- Font Awesome -->
        <link
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
            rel="stylesheet"
        />
        <!-- Google Fonts -->
        <link
            href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
            rel="stylesheet"
        />
        <!-- MDB -->
        <link
            href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css"
            rel="stylesheet"
        />
        <!-- Loading main css file -->
        <link rel="stylesheet" href="{% static 'css/style.css' %}" />

        <!--[if lt IE 9]>
            <script src="{% static 'js/ie-support/html5.js' %}"></script>
            <script src="{% static 'js/ie-support/respond.js' %}"></script>
        <![endif]-->
    </head>

    <body>
        <div class="site-content">
            {% if messages %} 
                {% for message in messages %} 
                    {% if message.tags == "error" %}
                    <div
                        class="alert alert-danger alert-dismissible fade show mx-1"
                        role="alert"
                    >
                        <strong>{{ message }}</strong>
                        <button
                            type="button"
                            class="btn-close"
                            data-mdb-dismiss="alert"
                            aria-label="Close"
                        ></button>
                    </div>
                    {% else %}
                    <div
                        class="alert alert-{{ message.tags }} alert-dismissible fade show mx-1"
                        role="alert"
                    >
                        <strong>{{ message }}</strong>
                        <button
                            type="button"
                            class="btn-close"
                            data-mdb-dismiss="alert"
                            aria-label="Close"
                        ></button>
                    </div>
                    {% endif %} 
                {% endfor %} 
            {% endif %} 

            {% include 'nav.html' %} 

            {% block content %} 
            {% endblock content %} 

            {% include 'footer.html' %}
        </div>
        <!-- JQuery -->
        <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
        <script src="{% static 'js/plugins.js' %}"></script>
        <script src="{% static 'js/app.js' %}"></script>
        <!-- MDB -->
        <script
            type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.js"
        ></script>
    </body>
</html>

templates/footer.html
{% load static %}

<footer class="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offseet-1">
                <p class="colophon">Copyright 2021 Django Solutions (Saman Zand). All rights reserved</p>
            </div>
            <div class="col-md-3 col-md-offset-3">
                <div class="social-links">
                    <a href="github.com/Saman-Zand-H"><i class="fab fa-github"></i></a>
                    <a href="#"><i class="fab fa-twitter"></i></i></a>
                    <a href="instagram.com/DjangoSolutions"><i class="fab fa-instagram"></i></a>
                    <a href="telegram.com/TCESaman"><i class="fab fa-telegram"></i></a>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/nav.html
{% load static %}

<div class="site-header">
    <div class="container">
        <a href="{% url 'wth:home' %}" class="branding">
            <img src="{% static 'images/raw-logo.png' %}" width="140" height="140" style="margin: -4rem;" alt="" class="logo">
            <div class="logo-type">
                <h1 class="site-title">Django Solutions</h1>
                <small class="site-description">Django always has a solution</small>
            </div>
        </a>

        <!-- Default snippet for navigation -->
        <div class="main-navigation mt-1">
            <button type="button" class="menu-toggle"><i class="fa fa-bars"></i></button>
            <!-- Menu -->
            <ul class="menu">
                <li class="menu-item current-menu-item"><a href="{% url 'wth:home' %}">Home</a></li>
                <li class="menu-item"><a href="{% url 'wth:contact' %}">Contact</a></li>
                {% if user.is_authenticated %}
                <li class="menu-item"><a href="{% url 'account_logout' %}">Log Out</a></li>
                <li class="menu-item">
                    <!-- Button trigger modal -->
                    <a
                    type="button"
                    data-mdb-toggle="modal"
                    data-mdb-target="#exampleModal"
                    >
                    {% if user.image %}
                            <img src="{{ user.image.url }}" class="img-fluid rounded-circle mx-2" width="35">
                        {% else %}
                            <img src="{% static 'images/empty.jpg' %}" class="img-fluid rounded-circle mx-2" width="35">
                        {% endif %}
                        Welcome, {{ user.username }}
                    </a>

                    <!-- Modal -->
                    <div
                    class="modal fade"
                    id="exampleModal"
                    tabindex="-1"
                    aria-labelledby="exampleModalLabel"
                    aria-hidden="true"
                    >
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header text-dark">
                                    <h1 class="modal-title" id="exampleModalLabel">Preferences</h1>
                                    <button
                                    type="button"
                                    class="btn-close"
                                    data-mdb-dismiss="modal"
                                    aria-label="Close"
                                    ></button>
                                </div>
                                <div class="modal-body">
                                    <!-- Set Unit Form -->
                                    <h2 class="text-dark">Unit</h2>
                                    <form action="{% url 'wth:unit' %}" method="POST" class="form-outline" id="unitForm">
                                        {% csrf_token %}
                                        <div class="form-floating">
                                            <select class="form-select" name="unit" id="Unit" aria-label="Unit">
                                                <option value="MET" selected>Metric</option>
                                                <option value="IMP">Imperial</option>
                                            </select>
                                            <label for="Unit"><b>Unit</b></label>
                                        </div>
                                        <a type="button" class="mt-3" onclick="$('#unitForm').submit()">Set unit</a>
                                    </form>
                                    {% if c_count > 1 %}
                                        <!-- Set Default City Form -->
                                        <hr>
                                        <h2 class="text-dark">Default City</h2>
                                        <form action="{% url 'wth:set-city' %}" method="POST" class="form-outline" id="defForm">
                                            {% csrf_token %}
                                            <div class="form-floating">
                                                <select class="form-select" name="default_city" id="DefaultCity">
                                                    {% for city in cities %}
                                                        <option value="{{ city }}">{{ city.city }}</option>
                                                    {% endfor %}
                                                </select>
                                                <label for="DefaultCity"><b>Cities</b></label>
                                            </div>
                                            <a type="button" class="mt-3" onclick="$('#defForm').submit()">Set default</a>
                                        </form>
                                    {% endif %}
                                    {% if c_count > 1 %}
                                        <!-- Remove City Form -->
                                        <hr>
                                        <h2 class="text-dark">Remove City</h2>
                                        <form action="{% url 'wth:remove-city' %}" method="POST" class="form-outline" id="rmForm">
                                            {% csrf_token %}
                                            <div class="form-floating">
                                                <select class="form-select" name="city" id="remCity">
                                                    {% for city in cities %}
                                                        <option value="{{ city }}">{{ city.city }}</option>
                                                    {% endfor %}
                                                </select>
                                                <label for="remCity"><b>Cities</b></label>
                                            </div>
                                            <a type="button" class="mt-3" onclick="$('#rmForm').submit()">Remove city</a>
                                        </form>
                                    {% endif %}
                                </div>
                                <div class="modal-footer">
                                    <a type="button" class="border-dark text-dark" data-mdb-dismiss="modal">Close</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
                {% else %}
                <li class="menu-item"><a href="{% url 'account_login' %}">Log In</a></li>
                <li class="menu-item"><a href="{% url 'account_signup' %}">Sign Up</a></li>
                {% endif %}
            </ul>
            <!-- Menu -->
        </div>
        <!-- Main-Navigation -->

        <div class="mobile-navigation"></div>

    </div>
</div>